services:
  - type: web
    name: bike-price-predictor
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
build:
  pythonVersion: 3.10
